### ISSUE TITLE
[BUG] Repeating manga clusters in search

### ISSUE THREAD

**Issue by minidukk** [Paperback-iOS/app#180]
**Describe the bug**
Since I updated IpadOS to 13.6 did this issue arises. When I use any kind of search in the app the first cluster of mangas shows up normally. But when I scroll down for the second cluster to load the first cluster shows up again. The same for every next clusters

**To Reproduce**
Search bar ---> any keywords ---> first cluster loads ---> scroll down to load ---> first cluster again

Search bar ---> any tags ---> first cluster loads ---> scroll down to load ---> first cluster again

Search bar ---> advance search ---> any tags or keyword ---> first cluster loads ---> scroll down to load ---> first cluster again

**Expected behaviour**
An update or a fix for this current version

**App Version**
App Store build v0.2.2

**Screenshots**
![manga](https://user-images.githubusercontent.com/69156687/89197845-8936a980-d5d6-11ea-8c36-0ccb91ae9a62.jpg)
![manga2](https://user-images.githubusercontent.com/69156687/89197951-ab302c00-d5d6-11ea-8954-768040973130.jpg)

also very sorry for the failed issue I just did before, super sorry in advance if that happens to this one too

**Comment by ConradWeiser** [comment]
Hi there,

This issue is fixed on the latest TestFlight build of Paperback.  v0.2.2 is really darned old, there have been a lot of changes (and bugfixes!) since then.

Please update, the problem should go away! Please give me a message, or join our Discord (found on https://paperback.moe) if you have any questions!

**Comment by FramboisePi** [comment]
Hi @ConradWeiser,

A similar problem seems to be still existing on MangaDex source on the latest alpha. 
Should I have open a new issue?

![MangaDex search issue](https://user-images.githubusercontent.com/25133304/96552680-6736f400-12b4-11eb-9033-e6db70327ccc.png)

Step to reproduce:
- Open search.
- Type a word (for example "Hana").
- Scroll through titles
You now see manga already shown at the top of the page.

---

App Version : v0.3.0-r11.0.33
Source : MangaDex
iOS 13.14.1

**Comment by ConradWeiser** [comment]
Hey there! For clarification, after you have updated the app, have you deleted the old "Official" repository, and refreshed the MangaDex source in the new source repository?

I suspect you have, I'd just to be sure before going forwards with this

**Comment by FramboisePi** [comment]
Technically speaking, I haven't, I did not update the app but made a fresh install... Thus I believe that should not be the issue.

Also I'm not sure if the first manga is always present more than one time but there is at least a repeated pattern on every search.

**Comment by FaizanDurrani** [comment]
Should be fixed, feel free to reopen this if its not.
