### ISSUE TITLE
[BUG] Issue with recent update sort order

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#576]
**Describe the bug**
In the “last updated” sort order, I have recently begun having an issue where the mangas suddenly move to an area at the bottom of the list after I view them. At first I thought they were disappearing altogether, but it seems they are still there, just accumulating at the bottom of the list. This is clearly not respecting my “last updated descending” sort order.

**To Reproduce**
Sort by last updated descending.  Then open up a manga and go back out of it. At least for me, it moves to a spot MUCH lower on the list. I’m not entirely sure how it picks the spot it moves to.  Not all manga seem to be affected, and I feel like it might be mixing in the “recently added” sort order or something, since many of the unaffected manga are recent additions to my library.  To fix the sort order, I have to remove and re-add the series to my library, or wait for another update to the series.

**Expected behavior**
It should keep it in the proper sort order.

**App Version**
0.7-r34+ (does not seem to happen on r31, but seems to happen on every version after that)
iOS 15.4.1
iPhone 13 Pro Max

**Screenshots**
Taken with r36
Start (sort order is “last updated” descending):
![8FBBF625-DD6D-44E6-9664-2D1833556D73](https://user-images.githubusercontent.com/657766/167265695-bbd1e233-8ff5-4375-a27c-7c66402470af.jpeg)
then, select the item in the center of the screen (which was in the right spot), and go back out:
![EC7AFD9C-8F1E-4324-92CD-F2D81E277A65](https://user-images.githubusercontent.com/657766/167265714-e2a8e54a-113e-4cce-b99e-4372626a2f1d.jpeg)
It’s now moved to a spot very close to the end of the list (the only ones after it are 4 series that have no chapters).

**Comment by FaizanDurrani** [comment]
This should be fixed in r40, reopen if it isn't

**Comment by henderea** [comment]
Well, I suppose it's an _improvement_, but now it seems to be moving stuff to the front of the list instead of the end.

Also, I'm having a hard time figuring out how to re-open the issue.  I can't see any buttons or options for it.

**Comment by henderea** [comment]
Not sure how to reopen, but I'm still having this issue, just with it going to the front of the list instead of the end. If I pick 2 series and switch between them, they keep moving every time.
