### ISSUE TITLE
[BUG] Device rotation from landscape back to portrait does not close the sidebar

### ISSUE THREAD

**Issue by kagari-mimi** [Paperback-iOS/app#592]
**Describe the bug**
When I'm in the library mode with the sidebar closed/hidden, rotating the device to landscape and back to portrait will cause the sidebar to slide in and reduce the width of the library instead of going on top of the library.

**To Reproduce**

1. Normal state, library in portrait orientation with sidebar closed.

    <img width="400" src="https://user-images.githubusercontent.com/105492782/169863867-9c464873-db1f-4cef-95e2-62761b27724c.PNG">

2. Rotating the device 90°, the library goes to landscape mode:

     <img width="600" src="https://user-images.githubusercontent.com/105492782/169864082-2a016dcd-d1f4-406d-94e7-b3785a12a3e2.PNG">

3. Rotating the device back, the sidebar shows up:

    <img width="400" src="https://user-images.githubusercontent.com/105492782/169864486-f552b716-35e0-47a0-b353-b9f39d44e573.jpg">

**Expected behaviour**
The sidebar should hide when coming back to portrait orientation.

**App Version**
Eg: v0.7-r42

---

Note: This bug, combined with the two-column layout introduced in v0.7-r40, caused the manga view to becoming hard to use on iPad mini, as the chapters list is now unreadable:

<img width="400" src="https://user-images.githubusercontent.com/105492782/169865444-75a68bfb-075e-46e7-820e-f95f4b6100b6.jpg">

Also, I notice that if I close and reopen the sidebar, the sidebar would overlay _on top_ of the library instead of slide in. I assume that this is actually the expected behavior:

<img width="400" src="https://user-images.githubusercontent.com/105492782/169865747-cd2a00fd-943a-4dbb-bdf8-e7c6219cef9e.jpg">

Thank you very much.

**Comment by Akiawa** [comment]
"Apparently fixed in r46"
Message link: https://discord.com/channels/673606787290759230/957820701044256889/983780261420478494

**Comment by yoBoss283** [comment]
> "Apparently fixed in r46"
> Message link: https://discord.com/channels/673606787290759230/957820701044256889/983780261420478494

Currently on r46. Can not confirm that it's fixed, similar behaviour when rotating as described.

**Comment by kagari-mimi** [comment]
Just want to drop a note that this still happens in v0.7-r47.

Again, the expected behavior should be for the sidebar to slide in when going from portrait to landscape, but hide again when the device goes back to portrait. Instead, currently, the sidebar is _not_ sliding in when going from portrait to landscape, but slides in when the device goes from landscape back to portrait, taking up the space.

I recently found a better workaround is to just press any other menu item on the bottom navigation bar and then press the old menu item again. (So, for example, if I was in a Libary tab and saw the issue, I tap Settings then tap Library again). So, I guess this is tolerable for now ...

**Comment by celarye** [comment]
As part of a repository-wide cleanup for the 0.9 release, we are resetting our issue tracker to more efficiently track new feedback and feature requests. If this issue is still relevant or critical to your workflow, please feel free to reopen it with updated context. Thank you for your support!
